language: bash

before_script:
    - sudo apt-get install --no-install-recommends libboost-dev libopenmpi-dev clang-3.9
    - sudo mv /usr/local/clang-5.0.0/bin/clang++ /usr/local/clang-5.0.0/bin/clang++.off
    - sudo mv /usr/local/clang-5.0.0/bin/clang /usr/local/clang-5.0.0/bin/clang.off
    - sudo update-alternatives --install /usr/bin/clang++ clang++ /usr/lib/llvm-3.9/bin/clang++ 100
    - sudo update-alternatives --install /usr/bin/clang clang /usr/lib/llvm-3.9/bin/clang 100

    - mv OpenFOAM-dev OpenFOAM-new
    - git clone --depth 1 https://github.com/OpenFOAM/OpenFOAM-dev.git
    - cp -R OpenFOAM-new/* OpenFOAM-dev
    
script:
    - cd OpenFOAM-dev
    - source etc/bashrc 
    - export WM_COMPILER=Clang
    - export WM_COMPILE_OPTION=FastCompilation
    - export MAKEFLAGS='-j4'

    - cd wmake/src 
    - make
    - cd ../..
    
    - cd src/OSspecific/POSIX/
    - ./Allwmake
    - cd ../../..
    
    - cd src
    - cd Pstream
    - wmake -j4 libso dummy
    - cd ..
    - wmake -j4 libso OpenFOAM
    - wmake -j4 libso fileFormats
    - wmake -j4 libso surfMesh
    - wmake -j4 libso triSurface
    - wmake -j4 libso meshTools
    - wmake -j4 libso finiteVolume
    - cd mesh
    - wmake -j4 libso extrudeModel
    - cd ..
    - wmake -j4 libso dynamicMesh
    - wmake -j4 libso dynamicFvMesh
    - wmake -j4 libso conversion
    - cd regionModels
    - wmake -j4 libso regionModel
    - cd ..
    - cd transportModels
    - wmake -j4 libso compressible
    - wmake -j4 libso twoPhaseMixture
    - wmake -j4 libso incompressible
    - cd ..    
    - cd thermophysicalModels
    - wmake -j4 libso specie
    - wmake -j4 libso SLGThermo
    - wmake -j4 libso thermophysicalProperties
    - wmake -j4 libso basic
    - wmake -j4 libso solidSpecie
    - wmake -j4 libso reactionThermo
    - wmake -j4 libso solidThermo
    - cd ..
    - cd lagrangian
    - wmake -j4 libso distributionModels
    - cd ..
    - cd regionModels
    - wmake -j4 libso surfaceFilmModels
    - cd ..
    - cd lagrangian
    - wmake -j4 libso basic
    - wmake -j4 libso solidParticle
    - cd ..
    - wmake -j4 libso sampling
    - cd TurbulenceModels
    - wmake -j4 libso turbulenceModels
    - wmake -j4 libso incompressible
    - wmake -j4 libso compressible
    - cd ..
    - wmake -j4 libso fvOptions
    - wmake -j4 libso radiationModels
    - cd lagrangian
    - wmake -j4 libso intermediate
    - wmake -j4 libso turbulence
    - cd ..
    - wmake -j4 libso topoChangerFvMesh
    - cd ..

    - cd applications/solvers/lagrangian/DPMFoam 
    - wmake -j4 all
    - cd ../../../..
