language: bash

before_script:
    - sudo apt-get install --no-install-recommends libboost-dev libopenmpi-dev clang-3.9
    - sudo mv /usr/local/clang-5.0.0/bin/clang++ /usr/local/clang-5.0.0/bin/clang++.off
    - sudo mv /usr/local/clang-5.0.0/bin/clang /usr/local/clang-5.0.0/bin/clang.off
    - sudo update-alternatives --install /usr/bin/clang++ clang++ /usr/lib/llvm-3.9/bin/clang++ 100
    - sudo update-alternatives --install /usr/bin/clang clang /usr/lib/llvm-3.9/bin/clang 100

    - mv OpenFOAM-dev OpenFOAM-new
    - git clone --depth 1 https://github.com/OpenFOAM/OpenFOAM-dev.git
    - cp -R OpenFOAM-new/* OpenFOAM-dev
    
script:
    - cd OpenFOAM-dev
    - source etc/bashrc 
    - export WM_COMPILER=Clang
    - export WM_COMPILE_OPTION=FastCompilation
      #- export WM_CXX=clang++-3.9
      #- export WM_CC=clang-3.9
    - export MAKEFLAGS='-j2'

    - cd wmake/src 
    - make
    - cd ../..
    
    - cd src/OSspecific/POSIX/
    - ./Allwmake
    - cd ../../..
    
    - cd src
    - cd Pstream
    - wmake -j2 libso dummy
    - cd ..
    - wmake -j2 libso OpenFOAM
    - wmake -j2 libso fileFormats
    - wmake -j2 libso surfMesh
    - wmake -j2 libso triSurface
    - wmake -j2 libso meshTools
    - wmake -j2 libso finiteVolume
    - cd mesh
    - wmake -j2 libso extrudeModel
    - cd ..
    - wmake -j2 libso dynamicMesh
    - wmake -j2 libso dynamicFvMesh
    - wmake -j2 libso conversion
    - cd regionModels
    - wmake -j2 libso regionModel
    - cd ..
    - cd transportModels
    - wmake -j2 libso compressible
    - wmake -j2 libso twoPhaseMixture
    - wmake -j2 libso incompressible
    - cd ..    
    - cd thermophysicalModels
    - wmake -j2 libso specie
    - wmake -j2 libso SLGThermo
    - wmake -j2 libso thermophysicalProperties
    - wmake -j2 libso basic
    - wmake -j2 libso solidSpecie
    - wmake -j2 libso reactionThermo
    - wmake -j2 libso solidThermo
    - cd ..
    - cd lagrangian
    - wmake -j2 libso distributionModels
    - cd ..
    - cd regionModels
    - wmake -j2 libso surfaceFilmModels
    - cd ..
    - cd lagrangian
    - wmake -j2 libso basic
    - wmake -j2 libso solidParticle
    - cd ..
    - wmake -j2 libso sampling
    - cd TurbulenceModels
    - wmake -j2 libso turbulenceModels
    - wmake -j2 libso incompressible
    - wmake -j2 libso compressible
    - cd ..
    - wmake -j2 libso fvOptions
    - cd lagrangian
    - wmake -j2 libso intermediate
    - wmake -j2 libso turbulence
    - cd ..
    - wmake -j2 libso topoChangerFvMesh
    - cd ..

    - cd applications/solvers/lagrangian/DPMFoam 
    - ./Allwmake
    - cd ../../../..
