language: bash

before_script:
    - sudo apt-get install libboost-dev libopenmpi-dev clang++-3.9

    - mv OpenFOAM-dev OpenFOAM-new
    - git clone --depth 1 https://github.com/OpenFOAM/OpenFOAM-dev.git
    - cp -R OpenFOAM-new OpenFOAM-dev
    
script:
    - cd OpenFOAM-dev
    - source etc/bashrc 
    - export WM_COMPILER=Gcc
    - export WM_COMPILE_OPTION=Debug
    - export MAKEFLAGS='-j 2'

    - cd wmake/src 
    - make
    - cd ../..
    
    - cd src/OSspecific/POSIX/
    - ./Allwmake
    - cd ../../..

    - cd src/Pstream
    - wmake libso dummy
    - cd ../..

    - cd src
    - wmake libso OpenFOAM
    - wmake libso fileFormats
    - wmake libso surfMesh
    - wmake libso triSurface
    - wmake libso meshTools
    - wmake libso finiteVolume
    - cd ..

    - cd src/lagrangian
    - ./Allwmake
    - cd ../..

    - cd applications/solvers/lagrangian/DPMFoam 
    - ./Allwmake
    - cd ../../../..
