language: bash

before_script:
    - sudo apt-get install --no-install-recommends libboost-dev libopenmpi-dev clang-3.9
    - sudo mv /usr/local/clang-5.0.0/bin/clang++ /usr/local/clang-5.0.0/bin/clang++.off
    - sudo mv /usr/local/clang-5.0.0/bin/clang /usr/local/clang-5.0.0/bin/clang.off
    - sudo update-alternatives --install /usr/bin/clang++ clang++ /usr/lib/llvm-3.9/bin/clang++ 100
    - sudo update-alternatives --install /usr/bin/clang clang /usr/lib/llvm-3.9/bin/clang 100

    - mv OpenFOAM-dev OpenFOAM-new
    - git clone --depth 1 https://github.com/OpenFOAM/OpenFOAM-dev.git
    - cp -R OpenFOAM-new/* OpenFOAM-dev
    
script:
    - cd OpenFOAM-dev
    - source etc/bashrc 
    - export WM_COMPILER=Clang
    - export WM_COMPILE_OPTION=FastCompilation
      #- export WM_CXX=clang++-3.9
      #- export WM_CC=clang-3.9
    - export MAKEFLAGS='-j'

    - cd wmake/src 
    - make
    - cd ../..
    
    - cd src/OSspecific/POSIX/
    - ./Allwmake
    - cd ../../..
    
    - cd src
    - cd Pstream
    - wmake -j libso dummy
    - cd ..
    - wmake -j libso OpenFOAM
    - wmake -j libso fileFormats
    - wmake -j libso surfMesh
    - wmake -j libso triSurface
    - wmake -j libso meshTools
    - wmake -j libso finiteVolume
    - cd mesh
    - wmake -j libso extrudeModel
    - cd ..
    - wmake -j libso dynamicMesh
    - wmake -j libso dynamicFvMesh
    - wmake -j libso conversion
    - cd regionModels
    - wmake -j libso regionModel
    - cd ..
    - cd transportModels
    - wmake -j libso compressible
    - wmake -j libso twoPhaseMixture
    - wmake -j libso incompressible
    - cd ..    
    - cd thermophysicalModels
    - wmake -j libso specie
    - wmake -j libso SLGThermo
    - wmake -j libso thermophysicalProperties
    - wmake -j libso basic
    - wmake -j libso solidSpecie
    - wmake -j libso reactionThermo
    - wmake -j libso solidThermo
    - cd ..
    - cd lagrangian
    - wmake -j libso distributionModels
    - cd ..
    - cd regionModels
    - wmake -j libso surfaceFilmModels
    - cd ..
    - cd lagrangian
    - wmake -j libso basic
    - wmake -j libso solidParticle
    - cd ..
    - wmake -j libso sampling
    - cd TurbulenceModels
    - wmake -j libso turbulenceModels
    - wmake -j libso incompressible
    - wmake -j libso compressible
    - cd ..
    - wmake -j libso fvOptions
    - cd lagrangian
    - wmake -j libso intermediate
    - wmake -j libso turbulence
    - cd ..
    - wmake -j libso topoChangerFvMesh
    - cd ..

    - cd applications/solvers/lagrangian/DPMFoam 
    - ./Allwmake
    - cd ../../../..
