language: bash

before_script:
    - sudo apt-get install libboost-dev libopenmpi-dev

    - mv OpenFOAM-dev OpenFOAM-new
    - git clone --depth 1 https://github.com/OpenFOAM/OpenFOAM-dev.git
    - cp -R OpenFOAM-new OpenFOAM-dev

script:
    - cd OpenFOAM-dev
    - source etc/bashrc 

    - cd wmake/src 
    - make
    - cd ../..
    
    - cd src/lagrangian
    - ./Allwmake
    - cd ../..

    - cd applications/solvers/lagrangian/DPMFoam 
    - ./Allwmake
    - cd ../../../..
